<?php
// src/Mdy/GstBundle/DataFixtures/ORM/Lieux.php

namespace Mdy\GstBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Mdy\GstBundle\Entity\Lieu;

class Lieux implements FixtureInterface{
	public function load(ObjectManager $manager){
		$listLieux = array(
					array('nom' => 'Hangars au zoning',
							'rue' => 'Avenue de Norvège',
							'numero' => ''),
					array('nom' => 'Fraternité',
							'rue' => 'Place de la Fraternité',
							'numero' => '2'),
					array('nom' => 'Hall des Sports',
							'rue' => 'Avenue du Pont de Warche',
							'numero' => '1'),
					array('nom' => 'Maison Vinette',
							'rue' => 'Rue Haute-Vaulx',
							'numero' => ''),
					array('nom' => 'Salle du Warhay',
							'rue' => 'Rue des Avrûles',
							'numero' => '5'),
					array('nom' => 'Ecole gardienne + crèche',
							'rue' => 'Ruelle des Capucins',
							'numero' => '2'),
					array('nom' => 'Gare',
							'rue' => 'Avenue de la Gare',
							'numero' => '24'),
					array('nom' => 'Ateliers Rue J. Werson',
							'rue' => 'Rue Joseph Werson',
							'numero' => '3'),
					array('nom' => 'Ecole Bellevaux',
							'rue' => 'Rue des Tilleuls',
							'numero' => '6'),
					array('nom' => 'Villa Steisel',
							'rue' => 'Place du Châtelet',
							'numero' => '2'),
					array('nom' => 'Ecole de Mont',
							'rue' => 'Route du Rôteu',
							'numero' => '1'),
					array('nom' => 'Salle de Musique - Xhoffraix',
							'rue' => '',
							'numero' => ''),
					array('nom' => 'Presbytère - Ligneuville',
							'rue' => '',
							'numero' => ''),
					array('nom' => 'Villa Lang',
							'rue' => 'Rue Jules Steinbach',
							'numero' => '2'),
					array('nom' => 'École des garçons',
							'rue' => 'Ruelle des Capucins',
							'numero' => '2'),
					array('nom' => 'Hôtel de Ville',
							'rue' => 'Rue Jules Steinbach',
							'numero' => '1'),
					array('nom' => 'Eglise des Capucins',
							'rue' => 'Ruelle des Capucins',
							'numero' => ''),
					array('nom' => 'Chalet Golf Miniature',
							'rue' => 'Parc des Tanneries',
							'numero' => ''),
					array('nom' => 'Pavillon Tennis',
							'rue' => 'Route de Falize',
							'numero' => ''),
					array('nom' => 'Piscine "Mon Repos"',
							'rue' => 'Avenue de la Libération',
							'numero' => '3'),
					array('nom' => 'École du Centre + Académie',
							'rue' => 'Ruelle des Capucins',
							'numero' => '2'),
					array('nom' => 'Arsenal Pompiers',
							'rue' => 'Rue Joseph Werson',
							'numero' => '1'),
					array('nom' => 'Chalet Athlétc Club',
							'rue' => 'Avenue du Pont de Warche',
							'numero' => '1'),
					array('nom' => 'Habitation Concierge école',
							'rue' => '',
							'numero' => ''),
					array('nom' => 'Maison Villers',
							'rue' => 'Chemin-Rue',
							'numero' => '11'),
					array('nom' => 'Serres',
							'rue' => 'Tridomez',
							'numero' => ''),
					array('nom' => 'Zone Infotourisme - Av. Libération',
							'rue' => 'Avenue de la Libération',
							'numero' => '3'),
					array('nom' => 'Maison du Tourisme',
							'rue' => 'Place Albert 1er',
							'numero' => '29A'),
					array('nom' => 'Zone Infotourisme - Géromont',
							'rue' => 'Route de Waimes',
							'numero' => ''),
					array('nom' => 'Zone Infotourisme - Av. des Alliés',
							'rue' => 'Avenue du Pont de Warche',
							'numero' => '1'),
					array('nom' => 'Camping - Sanitaire',
							'rue' => 'Route d\'Eupen',
							'numero' => '38'),
					array('nom' => 'Ecole de Chôdes',
							'rue' => 'Chemin des Écoliers',
							'numero' => '1'),
					array('nom' => 'Ecole de Longfaye',
							'rue' => 'Route de Hargister',
							'numero' => '1'),
					array('nom' => 'Ecole des Grands-Prés',
							'rue' => 'Avenue des Alliés',
							'numero' => '175'),
					array('nom' => 'Monastère',
							'rue' => 'Place du Châtelet',
							'numero' => '9'),
					array('nom' => 'Ecole de Ligneuville',
							'rue' => 'Route de Montenau',
							'numero' => '1'),
					array('nom' => 'Ecole de Pont',
							'rue' => 'Route Saint-Donat',
							'numero' => '2'),
					array('nom' => 'Ecole de Géromont',
							'rue' => 'Chemin du Léfâ',
							'numero' => '26'),
					array('nom' => 'Maison des Jeunes',
							'rue' => 'Rue Frédéric Lang',
							'numero' => '3'),
					array('nom' => 'Bâtiment Stocko',
							'rue' => 'Route de Falize',
							'numero' => '181'),
					array('nom' => 'Place du Parc - Bâtiment',
							'rue' => 'Place du Parc',
							'numero' => ''),
					array('nom' => 'Camping - Hangar',
							'rue' => 'Route d\'Eupen',
							'numero' => '38'),
					array('nom' => 'Salle de Chôdes',
							'rue' => 'Route du Barrage',
							'numero' => '40'),
					array('nom' => 'Croix-Rouge / Pétanque',
							'rue' => 'Rue Frédéric Lang',
							'numero' => ''),
					array('nom' => 'RCA / Malmedy Expo',
							'rue' => 'Rue Frédéric Lang',
							'numero' => '3')
					);
		foreach ($listLieux as $i => $lieux){
			$lieu = new Lieu();
			$lieu->setNom($lieux['nom']);
			$lieu->setRue($lieux['rue']);
			$lieu->setNumero($lieux['numero']);
			$manager->persist($lieu);
		}
		$manager->flush();
	}
}