<?php
/**
 * File :	ClotureRepository.php
 * Bundle : MdyGstBundle
 * Path :	src/Mdy/GstBundle/Entities
 * Since :	23/12/2015
 * Update :	23/12/2015
 * Author :	R. Threis
 */
namespace Mdy\GstBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClotureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClotureRepository extends EntityRepository
{
}
