<?php
/**
 * File :	EquipeRepository.php
 * Bundle : MdyGstBundle
 * Path :	src/Mdy/GstBundle/Entity
 * Since :	--
 * Update :	30/12/2015
 * Author :	R. Threis
 */
namespace Mdy\GstBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends EntityRepository {

	public function findForSelect(){
		return $this->createQueryBuilder('e')
					->orderBy('e.nom', 'ASC');
	}
	
	public function findDeleted(){
		$qb = $this->createQueryBuilder('e');
		$qb->where($qb->expr()->isNotNull('e.deletedAt'))
				->orderBy('e.nom', 'ASC');
		return $qb->getQuery()->getResult();
	}
	
	public function findNotDeleted(){
		$qb = $this->createQueryBuilder('e');
		$qb->where($qb->expr()->isNull('e.deletedAt'))
				->orderBy('e.nom', 'ASC');
		return $qb->getQuery()->getResult();
	}
	
	public function findEquipes($idIntervention){
		$qb = $this->createQueryBuilder('e')
					->join('e.interventions', 'intervention')
					->addSelect('intervention');
		$qb->andWhere($qb->expr()->eq('intervention.id', ':idIntervention'))
					->setParameter('idIntervention', $idIntervention)
					;
		return $qb;
	}
	
	public function statInEq(){
		$qb = $this->createQueryBuilder('equipe');
		$qb->select('equipe.nom as nom', 'count(inter.id) as total')
			->leftJoin('equipe.interventions', 'inter')
			->groupBy('equipe.nom')
			;
		return $qb->getQuery()->getResult();
	}
}
