<?php

namespace Mdy\GstBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemarqueRepository extends EntityRepository
{
}
