security:
    encoders:
        "Mdy\UserBundle\Entity\User": sha512

    role_hierarchy:
        # ROLE pour la GST
        ROLE_REDACTEUR:     [ROLE_USER]
        ROLE_SUPERVISEUR:   [ROLE_REDACTEUR]
        ROLE_DIRECTEUR:     [ROLE_SUPERVISEUR, ROLE_APPROBATEUR, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ECHEVIN:       [ROLE_UTILISATEUR, ROLE_APPROBATEUR, ROLE_ALLOWED_TO_SWITCH]
        #ROLE pour le XLA
        ROLE_XLA_REDACTEUR: [ROLE_USER]
        ROLE_XLA_EDITEUR:   [ROLE_XLA_REDACTEUR]
        ROLE_ADMIN:         [ROLE_SUPERVISEUR, ROLE_APPROBATEUR, ROLE_XLA_REDACTEUR, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:    ^/mdy/
            form_login:
                provider:   fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: mdy_core_index
                csrf_provider:  form.csrf_provider
                remember_me:   true
            logout:
                path:   fos_user_security_logout
                target: mdy_core_index
            remember_me:
                key:    %secret%
            anonymous:  true