<?php
/**
 * File :	ContactRepository.php
 * Bundle : MdyXlagendaBundle
 * Path :	src/Mdy/XlagendaBundle/Entity
 * Since :	17/09/2015
 * Update :	21/09/2015
 * Author :	R. Threis
 */
namespace Mdy\XlagendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository{
	
	public function getDeleted(){
		$qb = $this->createQueryBuilder('c');
		$qb->andWhere($qb->expr()->isNotNull('c.deletedAt'))
			->orderBy('c.nom', 'ASC')
			;
		return $qb->getQuery()->getResult();
	}
	
	public function getNotDeleted(){
		$qb = $this->createQueryBuilder('c');
		$qb->andWhere($qb->expr()->isNull('c.deletedAt'))
			->orderBy('c.nom', 'ASC')
			;
		return $qb->getQuery()->getResult();
	}
}
