<?php
/**
 * File :	LieuRepository
 * Bundle : MdyXlagendaBundle
 * Path :	src/Mdy/XlagendaBundle/Entity
 * Since :	06/08/2015
 * Update :	17/08/2015
 * Author :	R. Threis
 */
namespace Mdy\XlagendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuRepository extends EntityRepository
{
	public function findForSelect(){
		$qb = $this->createQueryBuilder('l');
		$qb->leftJoin('l.translations', 'lt')
			->where($qb->expr()->like('lt.locale', $qb->expr()->literal('fr')))
			->orderBy('lt.nom', 'ASC')
			;
		return $qb;
	}
	
	public function findAll(){
		$qb = $this->createQueryBuilder('l');
		$qb->leftJoin('l.translations', 'lt')
			->where($qb->expr()->like('lt.locale', $qb->expr()->literal('fr')))
			->andWhere($qb->expr()->isNull('l.deletedAt'))
			->orderBy('lt.nom', 'ASC')
			;
		return $qb->getQuery()->getResult();
	}
	
	public function exist(Lieu $lieu){
		// $nom = (!empty($lieu->getNom())) ? $lieu->getNom() : null;
		// $rue = (!empty($lieu->getRue())) ? $lieu->getRue() : null;
		// $num = (!empty($lieu->getNumero())) ? $lieu->getNumero() : null;
		// $localite = (!empty($lieu->getLocalite())) ? $lieu->getLocalite() : null;
		
		$qb = $this->createQueryBuilder('l');
		
	}
}
