<?php
/**
 * File :	RubriqueRepostory.php
 * Bundle : MdyXlagendaBundle
 * Path :	src/Mdy/XlagendaBundle/Entity
 * Since :	06/08/2015
 * Update :	17/08/2015
 * Author :	R. Threis
 */
namespace Mdy\XlagendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueRepository extends EntityRepository{
	
	public function findForList(){
		$qb = $this->createQueryBuilder('r');
		$qb->leftJoin('r.translations', 'rt')
			->where($qb->expr()->like('rt.locale', $qb->expr()->literal('fr')))
			->orderBy('rt.nom', 'ASC');
		return $qb;
	}
	
	public function findAll(){
		$qb = $this->createQueryBuilder('r');
		$qb->leftJoin('r.translations', 'rt')
			->where($qb->expr()->like('rt.locale', $qb->expr()->literal('fr')))
			->andWhere($qb->expr()->isNull('r.deletedAt'))
			->orderBy('rt.nom', 'ASC');
		return $qb->getQuery()->getResult();
	}
	
	public function findDeleted(){
		$qb = $this->createQueryBuilder('r');
		// $qb->leftJoin('r.translations', 'rt')
			$qb->where($qb->expr()->isNotNull('r.deletedAt'))
			// ->orderBy('rt.nom', 'ASC')
			;
		return $qb->getQuery()->getResult();
	}
	
	public function findNotDeleted(){
		$qb = $this->createQueryBuilder('r');
		// $qb->leftJoin('r.translation', 'rt')
			$qb->where($qb->expr()->isNull('r.deletedAt'))
			// ->orderBy('r.', 'ASC')
			;
		return $qb->getQuery()->getResult();
	}
}
