mdy_user_list:
    path:   /list
    defaults: { _controller: MdyUserBundle:User:list }

mdy_user_add:
    path:   /add
    defaults: { _controller: MdyUserBundle:User:add }

mdy_user_delete:
    path:   /delete/{id}
    defaults: { _controller MdyUserBundle:User:delete }
    requirements:
        id: \d+

mdy_user_edit:
    path:   /edit/{id}
    defaults: { _controller: MdyUserBundle:User:edit }
    requirements:
        id: \d+