# src/Mdy/CoreBundle/Resources/config/routing.yml
mdy_core_index:
    path:   /
    defaults: { _controller: MdyCoreBundle:Core:index }

mdy_gst:
    resource: "@MdyGstBundle/Resources/config/routing.yml"
    prefix:   /gst

mdy_user:
    resource: "@MdyUserBundle/Resources/config/routing.yml"
    prefix:   /user

# route pour le bundle FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# routes pour le bundle Xlagenda
mdy_xlagenda:
    resource: "@MdyXlagendaBundle/Resources/config/routing.yml"
    prefix:   /xla