services:
#    mdy_core.example:
#        class: Mdy\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    mdy_core.existor:
        class:  Mdy\CoreBundle\Existor\MdyExistor
        arguments:  [@doctrine.orm.entity_manager]